services:
  nextjs:
    build:
      context: ./nextjs
    ports:
      - "3000:3000"
    volumes:
      - ./nextjs:/src
      - /src/node_modules # This masks the node_modules directory from the host system and prevents it from being mapped from your local filesystem. The container will manage its own node_modules directory.
    working_dir: /src
    command: npm run dev

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: temp
      POSTGRES_PASSWORD: temp
      POSTGRES_DB: advcompro
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build: ./fastapi
    container_name: fastapi-app
    ports:
      - "8000:8000"
    environment:
      - FINNHUB_TOKEN=d3h8o3pr01qstnq865ngd3h8o3pr01qstnq865o0
    depends_on:
      - db

volumes:
  postgres_data: